var recipeData = [
  {'id': 0, 'name': 'chicken noodle soup', 'pic': 'images/fake_chicken_noodle_soup.png', 'category': ['water', 'chicken', 'onion', 'bay leaf', 'black pepper', 'celery', 'carrot', 'lemon grass', 'bouillon powder', 'celery', 'egg noodle', 'noodle'], 'ingredients': ['1 gallon water1 (4 pound) whole chicken, cut into pieces', '1 large onion, peeled and halved', '3 bay leaves', '10 whole black peppercorns', '2/3 bunch celery, leaves reserved', '1 pound whole carrots', '3 tablespoons chopped lemon grass (optional)', '1/4 cup chicken bouillon powder1 pound carrots, peeled and sliced', '1/3 bunch celery, chopped and leaves reserved', '1 (8 ounce) package dry egg noodles'], 'calories':303, 'servingSize': 12,'instructions':['1) Place chicken and water in a large pot over high heat and bring to a boil. Reduce heat, cover and simmer, skimming fat as needed, 30 minutes.', '2) Place the halved onion, bay leaves, peppercorns, whole celery, whole carrots and lemon grass in the pot and simmer, covered 1 hour.', '3) Strain broth and reserve chicken. When chicken is cool enough to handle, remove skin and cut meat into bite-size pieces.', '4) Return strained stock to pot over high heat, and stir in chicken base, chopped celery and chopped carrots. Bring to a boil, then reduce heat, cover and simmer 20 minutes, or until carrots are tender.', '5) Chop celery leaves and stir into pot with the noodles. Simmer until noodles are cooked, about 10 minutes more. Stir in chicken and heat through.'], 'time':'30'},
  {'id': 1, 'name': 'lasagna', 'pic': 'images/fake_lasagna.png', 'category': ['sausage', 'beef', 'onion', 'garlic', 'tomato', 'water', 'sugar', 'basil', 'fennel seeds', 'salt', 'black pepper', 'lasagna noodles', 'ricotta', 'egg', 'mozzarella cheese', 'parmesan cheese'], 'ingredients': ['1 pound sweet Italian sausage', '3/4 pound lean ground beef', '1/2 cup minced onion', '2 cloves garlic, crushed', '1 (28 ounce) can crushed tomatoes', '2 (6 ounce) cans tomato paste', '2 (6.5 ounce) cans canned tomato sauce', '1/2 cup water', '2 tablespoons white sugar', '1 1/2 teaspoons dried basil leaves', '1/2 teaspoon fennel seeds', '1 teaspoon Italian seasoning', '1 tablespoon salt', '1/4 teaspoon ground black pepper', '4 tablespoons chopped fresh parsley', '12 lasagna noodles', '16 ounces ricotta cheese', '1 egg', '1/2 teaspoon salt', '3/4 pound mozzarella cheese, sliced', '3/4 cup grated Parmesan cheese'], 'calories':448, 'servingSize': 12, 'instructions':['1) In a Dutch oven, cook sausage, ground beef, onion, and garlic over medium heat until well browned. Stir in crushed tomatoes, tomato paste, tomato sauce, and water. Season with sugar, basil, fennel seeds, Italian seasoning, 1 tablespoon salt, pepper, and 2 tablespoons parsley. Simmer, covered, for about 1 1/2 hours, stirring occasionally.', '2) Bring a large pot of lightly salted water to a boil. Cook lasagna noodles in boiling water for 8 to 10 minutes. Drain noodles, and rinse with cold water. In a mixing bowl, combine ricotta cheese with egg, remaining parsley, and 1/2 teaspoon salt.', '3) Preheat oven to 375 degrees F (190 degrees C).', '4) To assemble, spread 1 1/2 cups of meat sauce in the bottom of a 9x13 inch baking dish. Arrange 6 noodles lengthwise over meat sauce. Spread with one half of the ricotta cheese mixture. Top with a third of mozzarella cheese slices. Spoon 1 1/2 cups meat sauce over mozzarella, and sprinkle with 1/4 cup Parmesan cheese. Repeat layers, and top with remaining mozzarella and Parmesan cheese. Cover with foil: to prevent sticking, either spray foil with cooking spray, or make sure the foil does not touch the cheese.', '5) Bake in preheated oven for 25 minutes. Remove foil, and bake an additional 25 minutes. Cool for 15 minutes before serving.'], 'time' :'180'},
  {'id': 2, 'name': 'dumplings', 'pic': 'images/fake_dumplings.png', 'category': ['soy sauce', 'rice vinegar', 'chives', 'sesame seeds', 'garlic sauce', 'pork', 'garlic', 'egg', 'chive', 'sesame oil', 'ginger', 'dumpling wrapper', 'vegetable oil', 'water'], 'ingredients': ['1/2 cup soy sauce', '1 tablespoon seasoned rice vinegar', '1 tablespoon finely chopped Chinese chives', '1 tablespoon sesame seeds', '1 teaspoon chile-garlic sauce (such as Sriracha®)', '1 pound ground pork', '3 cloves garlic, minced', '1 egg, beaten', '2 tablespoons finely chopped Chinese chives', '2 tablespoons soy sauce', '1 1/2 tablespoons sesame oil', '1 tablespoon minced fresh ginger', '50 dumpling wrappers', '1 cup vegetable oil for frying', '1 quart water, or more as needed'], 'calories':540, 'servingSize': 5, 'instructions':['1) Combine 1/2 cup soy sauce, rice vinegar, 1 tablespoon chives, sesame seeds, and chile sauce in a small bowl. Set aside.', '2) Mix pork, garlic, egg, 2 tablespoons chives, soy sauce, sesame oil, and ginger in a large bowl until thoroughly combined. Place a dumpling wrapper on a lightly floured work surface and spoon about 1 tablespoon of the filling in the middle. Wet the edge with a little water and crimp together forming small pleats to seal the dumpling. Repeat with remaining dumpling wrappers and filling.', '3) Heat 1 to 2 tablespoons vegetable oil in a large skillet over medium-high heat. Place 8 to 10 dumplings in the pan and cook until browned, about 2 minutes per side. Pour in 1 cup of water, cover and cook until the dumplings are tender and the pork is cooked through, about 5 minutes. Repeat for remaining dumplings. Serve with soy sauce mixture for dipping.'], 'time' :'20'},
  {'id': 3, 'name': 'fried rice', 'pic': 'images/fake_fried_rice.png', 'category': ['rice', 'water', 'carrot', 'peas', 'vegetable oil', 'egg', 'soy sauce', 'sesame oil'], 'ingredients': ['2 cups enriched white rice', '4 cups water', '2/3 cup chopped baby carrots', '1/2 cup frozen green peas', '2 tablespoons vegetable oil', '2 eggs', 'soy sauce to taste', 'sesame oil, to taste (optional)'], 'calories':261, 'servingSize': 8, 'instructions':['1) In a saucepan, combine rice and water. Bring to a boil. Reduce heat, cover, and simmer for 20 minutes.', '2) In a small saucepan, boil carrots in water about 3 to 5 minutes. Drop peas into boiling water, and drain.', '3) Heat wok over high heat. Pour in oil, then stir in carrots and peas; cook about 30 seconds. Crack in eggs, stirring quickly to scramble eggs with vegetables. Stir in cooked rice. Shake in soy sauce, and toss rice to coat. Drizzle with sesame oil, and toss again.'], 'time' :'45'},
  {'id': 4, 'name': 'spaghetti and meatballs', 'pic': 'images/fake_Spaghetti_and_Meatballs.png', 'category': ['olive oil', 'beef', 'egg', 'milk', 'bread', 'salt', 'pepper', 'tomato', 'onion', 'garlic', 'oregano', 'basil', 'garlic salt', 'black pepper', 'sugar', 'spachetti noodle', 'noodle', 'parsley', 'parmesan cheese'], 'ingredients': ['2 tablespoons Extra Virgin Olive Oil', '1 1/2 pound ground beef', '2 eggs', '1/2 cup milk', '3/4 cup Italian bread crumbs', '1/4 teaspoon salt', '1/2 teaspoon pepper', '2 -14 ounce cans tomato sauce', '2 -14 ounce cans diced tomato', '1/2 large onion diced', '3 cloves garlic minced', '1 1/2 teaspoon oregano', '1 teaspoon basil', '1 tablespoon garlic salt', '1/4 teaspoon ground black pepper', '1 tablespoon light brown sugar', '1 pound uncooked spaghetti noodles', 'Fresh minced parsley and grated Parmesan cheese for topping'], 'calories':673, 'servingSize': 6, 'instructions':['1) Mix the ground beef, eggs, milk, bread crumbs, salt and pepper together in medium sized mixing bowl. Use hands to ensure thoroughly mixed.', '2) Using hands roll meatball mixture into small balls about 1 inch in diameter. Place into large saucepan coated with the olive oil.', '3) Cook the meatballs over medium heat, turning while they cook, until browned on all sides and cook through.', '4) Drain the grease from the pan.', '5) Return the pan to the stove at a low heat (keep the meatballs in the pan). Add the onion and cook until softened. Add the garlic and cook for an additional 30 seconds. Pour in the tomato sauce and diced tomatoes. Add in the oregano, basil, garlic salt, and black pepper. Stir to combine. Add in the light brown sugar and stir.', '6) Bring sauce to a simmer. Cover and cook for 30 minutes. 7) While the sauce is simmering cook the spaghetti noodles according to their directions. Combine the sauce and noodles together in the sauce pan, or just pour the sauce directly over the noodles. Add the Parmesan and enjoy!'], 'time' :'45'},
  {'id': 5, 'name': 'rosemary lemonade', 'pic': 'images/rosemary_lemonade.jpg', 'category': ['sugar', 'rosemary', 'lemon'], 'ingredients': ['1 cup sugar', '6 sprigs fresh rosemary', '2 cups fresh lemon juice (about 8 lemons)'], 'calories':143, 'servingSize': 6, 'instructions':['1) In a small saucepan, combine 1 cup water and sugar. Bring to a boil, stirring occasionally to dissolve sugar. Remove from heat and add rosemary. Cover saucepan and let cool, about 2 hours.', '2) Strain syrup into a pitcher. Stir in lemon juice and 3 cups cold water. Serve lemonade over ice.'], 'time' :'19'},
  {'id': 6, 'name': 'fish tacos with slaw', 'pic': 'images/fish_tacos.jpg', 'category': ['tilapia', 'salt', 'pepper', 'yogurt', 'lime', 'sesame oil', 'soy sauce', 'ginger', 'honey', 'tortilla'], 'ingredients': ['1 1/2 pounds tilapia fillets', 'Cooking spray', '1/4 teaspoon salt', '1/4 teaspoon pepper', '3 tablespoons plain low-fat Greek yogurt', '2 tablespoons lime juice', '1 tablespoon dark sesame oil', '1 tablespoon low-sodium soy sauce', '2 teaspoons grated peeled fresh ginger', '1 teaspoon honey', '3 cups shredded coleslaw mix', '12 (6-inch)  warmed corn tortillas'], 'calories':390, 'servingSize': 4, 'instructions':['1) Heat a nonstick skillet or grill pan over medium heat. Coat fish with cooking spray; sprinkle with salt and pepper. Add fish to pan; cook 10-12 minutes, turning once, until fish flakes easily with a fork.', '2) Combine yogurt and next 5 ingredients (through honey) in a small bowl, stirring with a whisk. Combine dressing and coleslaw mix, tossing to coat.', '3) Flake fish into pieces with a fork. Place 2 ounces fish in each tortilla. Top with coleslaw.'], 'time' :'20'},
  {'id': 7, 'name': 'spice-rubbed salmon steaks', 'pic': 'images/spice_rubbed_salmon.jpg', 'category': ['salmon', 'olive oil', 'red pepper', 'curry powder', 'salt', 'mashed potatoes'], 'ingredients': ['4 (6-ounce, 1-inch-thick) salmon steaks', '2 tablespoons extra-virgin olive oil', '1 teaspoon crushed red pepper', '2 teaspoons curry powder', '1/2 teaspoon salt', '2 cups mashed potatoes'], 'calories':444, 'servingSize': 4, 'instructions':['1) Combine the salmon, olive oil, red pepper, curry powder, and salt in a medium bowl. Coat salmon with the mixture.', '2) Heat a medium nonstick skillet over medium heat. Add the salmon steaks to the skillet, and cook about 4-5 minutes on 1 side. Flip over, and cook another 2-3 minutes or until completely cooked through.', '3) Place each steak on a plate, and serve with a side of mashed potatoes.'], 'time' :'16'},
  {'id': 8, 'name': 'potato-crusted spinach quiche', 'pic': 'images/potato_crusted_spinach_quiche.jpg', 'category': ['olive oil', 'potato', 'egg', 'flour', 'salt', 'spinach', 'onion', 'water', 'egg', 'ricotta', 'black pepper', 'swiss', 'canadian bacon'], 'ingredients': ['1 tablespoon olive oil divided', '1 (20-ounce) package refrigerated shredded potatoes (about 3 1/2 cups)', '1 large egg white whisked', '1 tablespoon all-purpose flour', '1/2 teaspoon salt', '6 ounces fresh spinach', '1/4 cup chopped onion', '2 tablespoons water', '6 large eggs', '1/4 cup part-skim ricotta cheese', '1/4 teaspoon freshly ground black pepper', '2 ounces Swiss cheese shredded (about 1/2 cup)', '1 ounce Canadian bacon finely chopped'], 'calories':380, 'servingSize': 4, 'instructions':['1) Preheat oven to 400°. Coat inside of a 9-inch deep-dish pie plate with 1 teaspoon olive oil; set aside.', '2) Combine potatoes and egg white in a large bowl; toss lightly. Add flour and salt; toss to coat. Transfer to pie plate, and pat evenly into bottom and sides to form crust. Drizzle remaining 2 teaspoons oil over crust. Bake at 400° for 15 minutes or until edges begin to brown. Remove from oven. Reduce oven temperature to 350°.', '3) While crust bakes, place spinach, onion, and 2 tablespoons water in a microwave-safe bowl. Microwave at HIGH 2 minutes or until spinach begins to wilt; drain. Place spinach mixture in a colander, and squeeze to drain; coarsely chop, and set aside.', '4) Combine eggs and ricotta cheese in a large mixing bowl; stir with a whisk until smooth. Add black pepper. Stir in spinach mixture, half of Swiss cheese, and bacon.', '5) Pour egg mixture over potato crust; spread with the back of a spoon to distribute evenly, leaving a 1/2-inch crust along the outer edge. Sprinkle remaining Swiss cheese on top. Bake at 350° for 5055 minutes, until puffed and golden. Cool on a wire rack 1015 minutes before serving. Slice into 4 equal pieces and serve.'], 'time' :'140'},
  {'id': 9, 'name': 'baby carrots with dill and lemon', 'pic': 'images/baby_carrots.jpg', 'category': ['chicken broth', 'carrot', 'butter', 'dill', 'chives', 'lemon', 'salt', 'black pepper'], 'ingredients': ['2 cups fat-free, less-sodium chicken broth', '2 pounds baby carrots, peeled and tops trimmed to 1 inch', '1 tablespoon butter', '2 teaspoons chopped fresh dill', '1 tablespoon chopped fresh chives', '1 tablespoon grated lemon rind', '1 tablespoon fresh lemon juice', '1/2 teaspoon salt', '1/2 teaspoon freshly ground black pepper'], 'calories':82, 'servingSize': 6, 'instructions':['Place broth in a large pot. Arrange carrots in a metal steamer insert or bamboo steamer; place in pot. Cover; bring broth to a boil. Steam carrots for 10 minutes or just until crisp-tender. Transfer carrots to a large bowl. Add remaining ingredients; toss well. Serve immediately.'], 'time' :'20'},
  {'id': 10, 'name': 'zucchini soup', 'pic': 'images/zucchini_soup.jpg', 'category': ['olive oil', 'onion', 'garlic', 'curry powder', 'potato', 'zucchini', 'chicken broth', 'salt', 'black pepper'], 'ingredients': ['1 tablespoon olive oil', '1 medium onion, chopped', '(1 1/2 cups)', '2 minced garlic cloves', '2 teaspoons curry powder', '1 large potato, peeled and diced', '2 medium zucchini, diced', '4 cups low-sodium chicken broth', '1/2 teaspoon salt', '1/4 teaspoon freshly ground black pepper'], 'calories':151, 'servingSize': 4, 'instructions':['In medium saucepan, heat oil over medium heat. Add onion; cook about 7-8 minutes, stirring occasionally. Add garlic and curry powder; cook, stirring, until fragrant (about 1 minute). Add remaining ingredients; heat to boiling. Reduce heat and simmer, covered, 20 minutes.'], 'time' :'29'},
  {'id': 11, 'name': 'fruit and vegetable salad', 'pic': 'images/fruit_and_vegetable_salad.jpeg', 'category': ['asparagus', 'carrot', 'mixed greens', 'strawberry', 'balsamic vinagrette', 'feta', 'goat cheese', 'pecan'], 'ingredients': ['1/2 pound asparagus spears, cut into bite-size pieces', '2 cups thinly sliced carrot', '8 cups mixed salad greens', '2 cups sliced strawberries', '1/2 cup light balsamic vinaigrette', '1 cup (4 ounces) crumbled goat or feta cheese', '1/2 cup pecan halves, toasted'], 'calories':227, 'servingSize': 4, 'instructions':['1) Bring a large saucepan filled with water to a boil. Prepare a bowl of ice water. Add asparagus and carrot to boiling water. Remove after 2 minutes, or when color has brightened; drain and plunge into ice water. Drain, and pat dry.', '2) Combine salad greens, strawberries, and vegetables. Add dressing; toss well before serving. Top with cheese and pecans.'], 'time' :'13'},
  {'id': 12, 'name': 'pork loin with chutney', 'pic': 'images/pork_loin.jpg', 'category': ['olive oil', 'water', 'pork', 'salt', 'pepper', 'bacon', 'leek', 'apple', 'cranberry', 'honey', 'rosemary', 'lemon juice', 'lemon'], 'ingredients': ['2 teaspoons olive oil', '1 (2 1/2-3 pound) boneless pork loin', '1/4 teaspoon kosher salt', '1/4 teaspoon pepper', '2 slices reduced-sodium bacon, sliced into 3/8-inch thick pieces', '1 medium leek, halved lengthwise and sliced into 1/2-inch-thick pieces (1 cup)', '3 medium apples, peeled, cored and sliced', '(3 1/2 cups) 1 cup fresh cranberries', '1 tablespoon honey', '1 small sprig fresh rosemary', '1 tablespoon fresh lemon juice', '1/3 cup water'], 'calories':291, 'servingSize': 8, 'instructions':['1) Preheat oven to 400°.', '2) Heat oil in a large nonstick skillet over medium-high heat until hot. Season pork with salt and pepper. Add pork to skillet, turning to brown on all sides, about 8 minutes. Transfer to a baking sheet (reserve skillet); roast 45-55 minutes or until an instant-read thermometer registers 155°. Remove from oven; transfer pork to a plate.', '3) Meanwhile, add bacon to skillet; cook over medium heat until bacon begins to crisp and fat has been released, about 3-4 minutes. Add leek and cook, stirring, until tender (about 8 minutes). Add apples, cranberries, honey, rosemary, lemon juice, and water. Bring to a boil; reduce heat and simmer, partially covered, for 30 minutes or until apples and cranberries partially break down and sauce thickens. Discard rosemary. Slice and serve pork with chutney and green beans or broccoli.'], 'time' :'60'},
  {'id': 13, 'name': 'cobb salad lettuce wraps', 'pic': 'images/cobb_salad_lettuce.jpg', 'category': ['mayonaise', 'red wine vinegar', 'black pepper', 'canadian bacon', 'lettuce', 'deli turkey', 'tomato', 'avocado', 'onion', 'red onion', 'blue cheese'], 'ingredients': ['4 tablespoons reduced-fat mayonnaise', '2 teaspoons red wine vinegar', '1/8 teaspoon black pepper', 'Cooking spray', '2 slices (2 ounces) Canadian bacon, diced', '1 head iceberg lettuce, outer leaves removed and discarded', '4 ounces smoked deli turkey breast slices, sliced into bite-size pieces', '1 large beefsteak tomato (about 3/4 pound), cored and cubed', '1/2 large peeled avocado, pitted and cubed', '1/2 small red onion, finely diced', '8 teaspoons crumbled blue cheese'], 'calories':177, 'servingSize': 4, 'instructions':['1) Combine mayonnaise, vinegar, and pepper; set aside.', '2) Heat a large nonstick skillet over medium-high heat; coat pan with cooking spray. Cook bacon until crisp (5-6 minutes), stirring occasionally. Remove bacon from skillet; pat with paper towels.', '3) Carefully separate 8 large leaves from lettuce head (do not tear) to use as wraps; reserve remaining lettuce for another use. Place 1 lettuce leaf inside another to create 4 (2-layered) wraps; fill with about 1/4 cup turkey breast, 1/4 of the cubed tomato (about 1/4 cup), 1/4 cup cubed avocado, and 2 tablespoons diced onion. Drizzle with 1 tablespoon reserved dressing; top with 1/4 of the crisped bacon and 2 teaspoons crumbled blue cheese.'], 'time' :'20'},
  {'id': 14, 'name': 'roast beef tenderloin', 'pic': 'images/roast_beef_tenderloin.jpg', 'category': ['thyme', 'garlic', 'salt', 'black pepper', 'beef'], 'ingredients': ['1 teaspoon dried thyme', '3 garlic cloves, minced', '1/2 teaspoon salt', '1/2 teaspoon black pepper', '1 (1 1/4 pound) center-cut beef tenderloin, trimmed', 'Cooking spray'], 'calories':246, 'servingSize': 4, 'instructions':['1) Preheat oven to 350°.', '2) Combine thyme, garlic, salt, and pepper; coat beef tenderloin with mixture. Heat a large ovenproof skillet coated with cooking spray over medium-high heat. Add beef; cook 2 minutes on 1 side until browned. Turn beef over.', '3) Transfer skillet to oven; bake at 350° for 20-25 minutes or until internal temperature reaches 125°. Transfer beef to a carving board; tent with foil, and let stand 10 minutes (internal temperature will rise to 130° for medium-rare).', '4) Cut beef crosswise into 8 slices; transfer to serving plates.'], 'time' :'16'},
  {'id': 15, 'name': 'salmon with lemon-mint crust', 'pic': 'images/salmon_with_lemon.jpg', 'category': ['lemon', 'salmon', 'salt', 'black pepper', 'garlic', 'bread', 'mint', 'olive oil', 'red pepper', 'spinach'], 'ingredients': ['1 small lemon', '1 1/4 pounds salmon fillet, preferably wild', '3/4 teaspoon kosher salt, divided', '1/2 teaspoon freshly ground black pepper, divided', '6 garlic cloves, peeled', '1 slice whole-wheat or multigrain bread', '1 teaspoon chopped fresh mint or 1/2 teaspoon dried mint flakes', '2 tablespoons extra-virgin olive oil', '1/16 teaspoon crushed red pepper', '16 ounces prewashed baby spinach'], 'calories': 364, 'servingSize': 4, 'instructions':['1) Preheat oven to 450°. Zest lemon. Transfer the zest to a food processor. Cut lemon into 4 wedges; set aside. Sprinkle salmon with 1/4 teaspoon salt and 1/4 teaspoon pepper.', '2) Coarsely chop 1 garlic clove and add it to the food processor. Thinly slice remaining garlic and set it aside.', '3) Tear the bread into chunks and add to the food processor along with mint, 1/4 teaspoon salt, and 1/4 teaspoon pepper. Process until coarse crumbs form and transfer to a small bowl. Stir in 1 teaspoon oil and set aside.', '4) Heat 2 teaspoons oil in ovenproof skillet over medium-high heat. Add salmon, skin-side up. Cook 3 minutes. Turn fish with spatula, pat crumbs over the surface, and transfer pan to the oven. Roast 5 minutes.', '5) While salmon cooks, heat remaining tablespoon oil in a large skillet over medium-high heat. Add sliced garlic and red pepper flakes. Sauté 1 minute, until garlic is lightly browned. Add spinach. Stir just until wilted, season with remaining 1/4 teaspoon salt, and toss. Divide among 4 dishes. Divide salmon into 4 portions; place fish on spinach. Serve with lemon wedges.'], 'time' :'24'},
  {'id': 16, 'name': 'rosemary garlic roast chicken', 'pic': 'images/rosemary_garlic.jpg', 'category': ['chicken', 'mustard', 'garlic', 'rosemary'], 'ingredients': ['1 (3 1/2- to 4-pound) whole chicken, raw with skin', '1/4 cup stone-ground mustard', '1 large garlic clove, minced', '1 1/2 tablespoons chopped fresh or 1 1/2 teaspoons dried rosemary'], 'calories':355, 'servingSize': 4, 'instructions':['1) Preheat oven to 375°.', '2) Rinse chicken with cold water; pat dry with a paper towel. Place chicken, breast side up, on a rack in a shallow foil-lined roasting pan or broiler pan. Starting at neck cavity of chicken, loosen skin from breast and drumsticks by inserting fingers between skin and meat and pushing gently. Combine mustard, garlic, and rosemary; rub under loosened skin, and rub over breast and drumsticks.', '3) Bake at 375° for 1 hour and 10 minutes or until internal temperature of thigh is 175°. Transfer the chicken to a carving board; let stand 5-10 minutes (temperature will rise to 180°). Carve chicken; transfer to serving plates.'], 'time' :'24'},
  {'id': 17, 'name': 'tomato and mozarrela melt', 'pic': 'images/tomato_and_mozzarella.jpg', 'category': ['bread', 'basil', 'tomato', 'mozzarella', 'orange'], 'ingredients': ['2 slices rye bread', '8 fresh basil leaves', '4 tomato slices', '2 (1-ounce) slices part-skim mozzarella cheese', '1 orange, cut into wedges'], 'calories': 370, 'servingSize': 1, 'instructions':['1) Top each bread slice with 4 basil leaves, 2 tomato slices, and 1 slice cheese.', '2) Melt open-faced sandwiches in toaster oven or broiler 4 to 5 minutes, until cheese is bubbling. Serve with orange wedges.'], 'time' :'25'},
  {'id': 18, 'name': 'pepper steak fajitas', 'pic': 'images/pepper_steak_fajitas.jpg', 'category': ['garlic', 'lime', 'chili powder', 'steak', 'olive oil', 'bell pepper', 'cumin', 'tortilla', 'avocado', 'sour cream', 'cilantro'], 'ingredients': ['3 cloves garlic, minced', '3 tablespoons fresh lime juice', '1/2 teaspoon chili powder', '1 1/2 pounds skirt steak, cut crosswise to fit in skillet (about 3 pieces)', '2 tablespoons olive oil', '3 large bell peppers, any color, seeded and sliced', '1 teaspoon cumin seeds', '12 6-inch whole-wheat tortillas', 'Sour cream, avocado, cilantro and lime wedges, optional'], 'calories': 427, 'servingSize': 6, 'instructions':['1) In a shallow glass dish, stir together garlic, lime juice and chili powder. Add steak, turn to coat and let stand for 5 minutes, turning occasionally.', '2) In a large nonstick or seasoned cast-iron skillet, warm 1 Tbsp. oil over medium-high heat. Cook bell peppers, stirring occasionally, for 4 minutes. Add cumin seeds; continue to sauté until bell peppers are lightly browned and tender, about 2 minutes more. Transfer to a platter.', '3) Add remaining 1 Tbsp. oil to skillet. Add steak and cook, turning once, until browned, about 6 minutes for medium-rare. Transfer to a cutting board and let stand for 5 minutes before slicing thinly against the grain.', '4) Top tortillas with bell peppers and steak. Serve with additional toppings such as sour cream, avocado, cilantro and lime wedges, if desired.'], 'time' :'26'},
  {'id': 19, 'name': 'broccoli and feta omelet with toast', 'pic': 'images/broccoli_and_feta.png', 'category': ['broccoli', 'egg', 'feta cheese', 'dill', 'bread'], 'ingredients': ['Cooking spray', '1 cup chopped broccoli', '2 large eggs, whisked', '2 tablespoons Feta cheese, crumbled', '1/4 teaspoon dried dill', '2 slices rye bread, toasted'], 'calories': 390, 'servingSize': 1, 'instructions':['1) Heat a nonstick skillet over medium heat. Coat pan with cooking spray. Add broccoli, and cook 3 minutes.', '2) Combine eggs, Feta, and dill in a small bowl. Add egg mixture to pan. Cook 34 minutes; fold in half with a spatula and cook 2 more minutes or until cooked through. Serve with toast.'], 'time' :'10'},
  {'id': 20, 'name': 'shrimp scampi with broccoli noodles', 'pic': 'images/shrimp_scampi.jpg', 'category': ['broccoli', 'olive oil', 'black pepper', 'garlic', 'shrimp', 'white wine', 'lemon', 'butter', 'basil', 'chives', 'red pepper'], 'ingredients': ['2 large heads broccoli with long stems', '2 tablespoons olive oil, divided', 'salt and ground black pepper to taste', '2 cloves garlic, minced', '1 pound raw shrimp, peeled and deveined', '2 tablespoons dry white wine', '2 tablespoons lemon juice', '2 tablespoons butter', '1 tablespoon minced fresh basil', '1 tablespoon chopped fresh chives', '1/2 teaspoon crushed red pepper'], 'calories': 267, 'servingSize': 4, 'instructions':['1) Cut off broccoli florets and save for another use. Cut woody ends off the stems. Shave large knots off the stems using a vegetable peeler so that they are as uniform as possible. Cut into noodles using the smallest blade on a spiralizer.', '2) Heat 1 tablespoon olive oil in a large skillet over medium-high heat. Add broccoli noodles, salt, and pepper; toss for 3 minutes. Remove from heat and set aside.', '3) Heat remaining olive oil and garlic in a separate skillet over medium heat. Cook for 1 minute. Add shrimp and cook until opaque, about 3 minutes per side. Transfer shrimp to a bowl.', '4) Add wine, lemon juice, butter, basil, chives, and red pepper to the skillet. Whisk over medium heat for 3 minutes. Return shrimp to the skillet and toss to coat.', '5) Spoon broccoli noodles into 4 serving bowls. Top with shrimp mixture.'], 'time' :'25'},
  {'id': 21, 'name': 'chicken and broccoli', 'pic': 'images/fake_Chicken_and_Broccoli.png', 'category': ['soy sauce', 'brown sugar', 'ground ginger', 'red pepper flakes', 'water', 'cornstarch', 'vegetable oil', 'chicken', 'onion', 'broccoli'], 'ingredients': ['2/3 cup soy sauce', '1/4 cup brown sugar', '1/2 teaspoon ground ginger', '1 pinch red pepper flakes, or to taste', '2 tablespoons water', '2 tablespoons cornstarch', '2 teaspoons vegetable oil, or to taste', '3 skinless, boneless chicken breast halves, cut into chunks', '1 onion, sliced', '3 cups broccoli florets'], 'calories': 356, 'servingSize': 3, 'instructions':['1) Stir soy sauce, brown sugar, ginger, and red pepper flakes together in a bowl to dissolve sugar into the liquid. Mix water and cornstarch together in a small bowl; stir with a whisk until cornstarch dissolves completely.', '2) Heat oil in a large skillet over high heat. Fry chicken and onion in hot oil until the chicken is no longer pink in the center and the onion is tender, 5 to 7 minutes. Stir broccoli with the chicken and onion; saute until the broccoli is hot, about 5 minutes. Push the chicken and vegetables mixture to the side of the skillet.', '3) Pour the soy sauce mixture into the vacant part of the skillet. Stir the cornstarch slurry into the soy sauce mixture until the color is consistent. Move the chicken and vegetables back into the center to the pan; saute until the sauce thickens and coats the chicken and vegetables, about 5 minutes more.'], 'time' :'15'},
  {'id': 22, 'name': 'lemon rosemary chicken', 'pic': 'images/fake_Lemon_Rosemary_Chicken.png', 'category': ['butter', 'rosemary', 'garlic', 'lemon', 'lemon juice', 'chicken', 'salt', 'pepper'], 'ingredients': ['1/2 cup butter', '1/2 cup fresh rosemary', '3 cloves garlic', '1 lemon, zested', '1/4 cup fresh lemon juice', '6 (6 ounce) skinless, boneless chicken breast halves', 'salt and pepper to taste'], 'calories': 331, 'servingSize': 6, 'instructions':['1) In a food processor, thoroughly blend together the butter, rosemary, garlic, lemon zest, and lemon juice. Pour 1/3 of blended mixture into a small bowl for marinade. Cover remaining mixture, and set aside.', '2) Lightly season chicken breasts with salt and pepper. Rub chicken breasts with the marinade mixture. Place chicken breasts on a platter, cover, and refrigerate 3 hours.', '3) Preheat an outdoor grill for high heat and lightly oil grate. Pour half of the reserved rosemary and lemon mixture into a bowl for basting. Cover remaining mixture, and set aside for topping cooked chicken.', '4) Grill chicken breasts 4 minutes on each side, basting with rosemary and lemon basting mixture. Remove chicken breasts from grill, and top with small scoops of the remaining topping mixture.'], 'time' :'15'},
  {'id': 23, 'name': 'cauliflower breadsticks', 'pic': 'images/fake_Cauliflower_Breadsticks.png', 'category': ['cauliflower', 'egg', 'mozzarella cheese', 'black pepper', 'salt', 'marinara sauce'], 'ingredients': ['1 large head of cauliflower (7″ – 8″ wide and 3-3.5 lbs) or 1 bag of store bought cauliflower rice', '1/4 cup egg whites or 2 large eggs', '1/2 cup + 3/4 cup (for topping) Mozzarella/Tex Mex cheese, shredded', '1 tsp Italian seasoning (dried oregano or basil)', '1/4 tsp ground black pepper', 'Pinch of salt', 'Marinara sauce for dipping', 'Cooking spray'], 'calories': 51, 'servingSize': 12, 'instructions':['1) Preheat oven to 375 degrees F. Rinse cauliflower, remove outer leaves and separate into florets with a paring knife. Place cauliflower florets in a food processor and process until “rice” texture. Some coarse chunks are fine.', '2) Place in an ovenproof baking dish (I used Pyrex pie dish) and bake for 20 mins. Remove cooked cauliflower from the oven and transfer to a bowl lined with a tea/linen towel. Let the cauliflower cool down a bit until it is safe to touch, about 15 minutes.', '3) Fold the towel holding by the ends and squeeze the liquid out of the cauliflower “ball” as hard as you can. Be patient and do this a few times until barely any liquid comes out. I squeezed out 1 cup of liquid. Second photo, from right to left: before squeezing, after squeezing, liquid squeezed out.', '4) Increase oven T to 450 degrees F. Transfer cauliflower to a mixing bowl along with egg whites, 1/2 cup cheese, herb seasoning, black pepper, pinch of salt and mix to combine.', '5) Transfer cauliflower mixture onto the baking sheet lined with unbleached parchment paper. Flatten with your hands into a rectangle, approximately 9″ x 7″ size and 1/4″ thick.', '6) Bake for 18 minutes, remove from the oven and top with remaining 3/4 cup cheese. Bake for another 5 minutes and then broil until cheese turns golden brown. Cut into 12 breadsticks and serve hot with warm marinara sauce, if desired. P.S. For a lighter version, do not top with cheese.'], 'time' :'50'},
  {'id': 24, 'name': 'spicy buffalo tacos', 'pic': 'images/fake_Spicy_Buffalo_Tacos.png', 'category': ['tortilla', 'guacamole', 'chicken', 'hot sauce', 'bell pepper', 'red onion', 'cilantro', 'carrot', 'baby carrot', 'celery'], 'ingredients': ['8 Mission® Soft Taco Flour Tortillas', '1 cup Mission® Guacamole Flavored Dip', '1 pound skinless boneless chicken breasts', '3 tablespoons cayenne pepper hot sauce', 'Non-stick cooking spray to coat', '1 green bell pepper, cut into thin strips', '1/2 red onion, cut into thin strips', '1/2 cup cilantro leaves', '12 baby carrots, rinsed', '12 celery sticks', '1 cup prepared blue cheese dressing'], 'calories': 760, 'servingSize': 4, 'instructions':['1) Pre-heat charcoal or indoor grill to medium-high heat.', '2) Place cleaned chicken breasts into a gallon-size zipper storage bag, add hot sauce and toss; close and refrigerate for 30 minutes.', '3) After 30 minutes remove chicken from refrigerator. Spray each side of the marinated chicken with non-stick cooking spray; place on pre-heated grill and cook for 8 minutes per side or until cooked through. Place cooked chicken onto your work surface and allow to cool for a few minutes. Slice each chicken breast into thin strips cutting across the breast.', '4) Warm Mission(R) Tortillas. Evenly spread 1 tablespoon of Mission(R) Guacamole Flavored Dip edge to edge.', '5) Lay 5-6 slices of chicken across the middle of each tortilla, top chicken with 5 strips of green bell pepper, red onion and a tablespoon of cilantro leaves.', '6) Starting at the bottom roll tortilla forward to form a cylinder, repeat process for remaining tortillas.', '7) Serve a portion of tacos (two tacos) with 3 baby carrots, 3 celery sticks and a 1/4 cup of blue cheese dressing in a small ramekin.'], 'time' :'30'},
]

var myFavorite = [
  recipeData[0],
  recipeData[1],
  recipeData[2],
  recipeData[3]
]
var myKitchen = [
  {'id':0, 'category': 'Fruits', 'items': ['apple', 'banana', 'pear', 'strawberry']},
  {'id':1, 'category': 'Protein', 'items': ['beef','tilapia', 'pork']},
  {'id':2, 'category': 'Vegetables', 'items': ['carrot', 'spinach', 'broccoli', 'onion', 'garlic']},
  {'id':3, 'category': 'Diary', 'items': ['milk','cheese', 'feta']},
  {'id':4, 'category': 'Oil', 'items': ['olive oil', 'vegetable oil']},
  {'id':5, 'category': 'Others', 'items': ['noodle', 'lasagna noodle', 'salt', 'black pepper']}
]

//get username and password
var name = localStorage.getItem('customName');
var pass = localStorage.getItem('password');
$("#myusername").html(name);
$("#mypassword").html(pass);

//function for updating inputted login to local storage
function loginFunction() {
  //getting and setting username
  var name = localStorage.getItem('customName');
    if (true) {
      $("#myusername").html(name);

    var username = document.getElementById("username").value;
    console.log(name);
    localStorage.setItem('customName', username);
    console.log(username);
  }

  //getting and setting password
  var pass = localStorage.getItem('password');
    if (true) {
      $("#mypassword").html(pass);

      var mypass = document.getElementById("password").value;
      console.log(pass);
      localStorage.setItem('password', mypass);
      console.log(mypass);
    }
    //opens homepage after script runs
    localStorage.setItem('favData',JSON.stringify(myFavorite));
    localStorage.setItem('myKitchen',JSON.stringify(myKitchen));
    localStorage.setItem('recipeData', JSON.stringify(recipeData));
    localStorage.setItem('firstLogin', JSON.stringify("1"));
    $('#b').fadeOut(1000, function(){
      window.location = "homepage.html?";
    });
    /*window.location = "homepage.html?";*/
}
